routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::resource('region', 'RegionController')->middleware('auth');
Route::resource('user', 'UserController')->middleware('auth');
Route::resource('role', 'RoleController')->middleware('auth');
Route::resource('assignment', 'AssignmentController')->middleware('auth');
Route::resource('permission', 'PermissionController')->middleware('auth');
Route::resource('crd', 'CrdController')->middleware('auth');
Route::resource('erb', 'ErbController')->middleware('auth');
Route::resource('counter', 'CounterController')->middleware('auth');
Route::resource('qr', 'QrController')->middleware('auth');
Route::resource('nfc', 'NfcController')->middleware('auth');
Route::get('sensor/chart/{id}', 'SensorController@chart')->name('sensor.chart')->middleware('auth');
Route::resource('sensor', 'SensorController')->middleware('auth');
Route::resource('statistical', 'StatisticalController')->middleware('auth');
Route::resource('probeestimating', 'ProbeEstimatingController')->middleware('auth');
Route::resource('classname', 'ClassNameController')->middleware('auth');
Route::resource('file', 'FileController')->middleware('auth');
Route::resource('historialcounter', 'HistorialCounterController')->middleware('auth');
Route::resource('historialcrd', 'HistorialCrdController')->middleware('auth');
Route::resource('historialerb', 'HistorialErbController')->middleware('auth');
Route::resource('historialqr', 'HistorialQrController')->middleware('auth');
Route::resource('historialnfc', 'HistorialNfcController')->middleware('auth');
Route::get('historialsensor/chart/{id}', 'HistorialSensorController@chart')->name('historialsensor.chart')->middleware('auth');
Route::resource('historialsensor', 'HistorialSensorController')->middleware('auth');
Route::resource('historialstatistical', 'HistorialStatisticalController')->middleware('auth');
Auth::routes();

app/Http/Controllers/Api/NfcController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
//use App\Http\Controllers\Controller;
use App\Http\Controllers\Api\BaseController as BaseController;
use App\Nfc;
use App\HistorialNfc;
use Validator;

class NfcController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $nfc = Nfc::all();
        $data = $nfc->toArray();
        $response = [
            'success' => true,
            'data' => $data,
            'message' => 'Nfc retrieved successfully'
        ]; 
        return response()->json($response, 200);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**updthistialsnfc
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // 'id',  'num_serie', 'key_1', 'key_2', 'key_3', 'key_4', 'key_5', 'ssid', 
       //'password', 'dns_server', 'ip_server', 'protocol', 'port', 'text',
       $validator = Validator::make($request->all(), [
        'num_serie'=>'required|string|max:100',
        'key_1'=>'required|string|max:100',
        'key_2'=>'required|string|max:100',
        'key_3'=>'required|string|max:100',
        'key_4'=>'required|string|max:100',
        'key_5'=>'required|string|max:100',
        'ssid'=>'required|string|max:100',
        'password'=>'required|string|max:100',
        'dns_server'=>'required|string|max:100',
        'ip_server'=>'required|string|max:100',
        'protocol'=>'required|string|max:100',
        'port'=>'required|string|max:100',
        'text'=>'required|string|max:100',
    ]);

    if ($validator->fails()) {
        $response = [
            'success' => false,
            'data' => 'Validation Error.',
            'message' => $validator->errors()
        ];
        return response()->json($response, 404);
    }
    $data = 'Please register correctly Nfc';

    if($request->get('password') == 'nfc123'){
    $ssid = (Nfc::all()->count() + 1);
    $nfc = new Nfc();
    $nfc->esp32_id = null;
    $nfc->raspberry_id = null;
    $nfc->num_serie = $request->get('num_serie');
    $nfc->key_1 = $request->get('key_1');
    $nfc->key_2 = $request->get('key_2');
    $nfc->key_3 = $request->get('key_3');
    $nfc->key_4 = $request->get('key_4');
    $nfc->key_5 = $request->get('key_5');
    $nfc->ssid = 'nfc_'.$ssid;
    $nfc->password = Crypt::encrypt($request->get('password'));
    $nfc->dns_server = $request->get('dns_server');
    $nfc->ip_server = $request->get('ip_server');
    $nfc->protocol = $request->get('protocol');
    $nfc->port = $request->get('port');
    $nfc->text = $request->get('text');
    $nfc->save();
    $data = $nfc->toArray();
    $response = [
        'success' => true,
        'data' => $data,
        'message' => 'Nfc register successfully.'
    ]; 
    return response()->json($response, 200);
    }
    else{
    $data = 'Register_Error';
    $response = [
        'success' => true,
        'data' => $data,
        'message' => 'Nfc not registered.'
    ]; 
    }
    return response()->json($response, 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function historialnfc(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'json' => 'required|string',
        ]);

        if ($validator->fails()) {
            $response = [
                'success' => true,
                'data' => 'Parameter Error.',
                'message' => $validator->errors()
            ];
            return response()->json($response, 200);
        }

        $parse_json = json_decode($request->get('json'), true);
        foreach ($parse_json as $key => $json) {
        $historial_upload = new HistorialNfc();
        $historial_upload->nfc_coin_id  = $json['nfc_coin_id'];
        $historial_upload->name_machine  = $json['name_machine'];
        $historial_upload->nick_name  = $json['nick_name'];
        $historial_upload->nfc_serie  = $json['nfc_serie'];
        $historial_upload->coins = $json['coins'];	
        $historial_upload->uploaded = 1;
        $historial_upload->created_at = $json['created_at'];
        $historial_upload->save();
        ////////////////////////////////////////////
        $nfc = NfcCoin::find($json['nfc_coin_id']);
        $nfc->coins = $json['coins'];
        $nfc->save();
        ////////////////////////////////////////////
        }
        $data = 'Upload Exitoso';
            $response = [
                'success' => true,
                'data' => $data,
                'message' => 'Todo OK'
            ];
            return response()->json($response, 200); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($num_serie)
    {
        //
        $nfc = Nfc::where('num_serie',$num_serie)->first();
        if(is_null($nfc)){
            $response = [
                'success' => false,
                'data' => 'Empty',
                'message' => 'Nfc not Exist'
            ];
            return response()->json($response, 404);
        }
        $data = $nfc->toArray();
        $response = [
            'success' => true,
            'data' => $data,
            'message' => 'Nfc retrieved successfully.'
        ];
        return response()->json($response, 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Nfc $nfc)
    {
        // 'id',  'num_serie', 'key_1', 'key_2', 'key_3', 'key_4', 'key_5', 'ssid', 
        //'password', 'dns_server', 'ip_server', 'protocol', 'port', 'text',
        $input = $request->all();
        $validator = Validator::make($input, [
            'esp32_id'=>'required|string|max:100',
            'raspberry_id'=>'required|string|max:100',
            'num_serie'=>'required|string|max:100',
            'key_1'=>'required|string|max:100',
            'key_2'=>'required|string|max:100',
            'key_3'=>'required|string|max:100',
            'key_4'=>'required|string|max:100',
            'key_5'=>'required|string|max:100',
            'ssid'=>'required|string|max:100',
            'password'=>'required|string|max:100',
            'dns_server'=>'required|string|max:100',
            'ip_server'=>'required|string|max:100',
            'protocol'=>'required|string|max:100',
            'port'=>'required|string|max:100',
            'text'=>'required|string|max:100',
        ]);

        if ($validator->fails()) {
            $response = [
                'success' => false,
                'data' => 'Validation Error.',
                'message' => $validator->errors()
            ];
            return response()->json($response, 404);
        }

        $nfc->esp32_id = $input['esp32_id'];
        $nfc->raspberry_id = $input['raspberry_id'];
        $nfc->num_serie = $input['num_serie'];
        $nfc->key_1 = $input['key_1'];
        $nfc->key_2 = $input['key_2'];
        $nfc->key_3 = $input['key_3'];
        $nfc->key_4 = $input['key_4'];
        $nfc->key_5 = $input['key_5'];
        $nfc->ssid = $input['ssid'];
        $nfc->password = Crypt::encrypt($request->get('password'));
        $nfc->dns_server = $input['dns_server'];
        $nfc->protocol = $input['protocol'];
        $nfc->port = $input['port'];
        $nfc->text = $input['text'];
        $nfc->save();
        $data = $nfc->toArray();
        $response = [
            'success' => true,
            'data' => $data,
            'message' => 'Nfc updated successfully.'
        ];
        return response()->json($response, 200);
    }

     /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function modify(Request $request)
    {
        // 'id', 'user_id', 'num_serie', 'nick_name', 'password', 'api_token',
        $input = $request->all();
        $validator = Validator::make($input, [
            'esp32_id'=>'required|string|max:100',
            'raspberry_id'=>'required|string|max:100',
            'num_serie'=>'required|string|max:100',
            'key_1'=>'required|string|max:100',
            'key_2'=>'required|string|max:100',
            'key_3'=>'required|string|max:100',
            'key_4'=>'required|string|max:100',
            'key_5'=>'required|string|max:100',
            'ssid'=>'required|string|max:100',
            'password'=>'required|string|max:100',
            'dns_server'=>'required|string|max:100',
            'ip_server'=>'required|string|max:100',
            'protocol'=>'required|string|max:100',
            'port'=>'required|string|max:100',
            'text'=>'required|string|max:100',
        ]);

        if ($validator->fails()) {
            $response = [
                'success' => false,
                'data' => 'Validation Error.',
                'message' => $validator->errors()
            ];
            return response()->json($response, 404);
        }
        $nfc = Nfc::where('num_serie',$input['num_serie'])->first(); 
        if (is_null($nfc)) {
            $response = [
                'success' => false,

app/Http/Controllers/NfcController.php
<?php

namespace App\Http\Controllers;

use App\Nfc;
use App\Crd;
use App\Erb;
use Illuminate\Http\Request;

class NfcController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $nfcs = Nfc::all();
        //return view('module.nfc.index')->with('nfs',$nfcs);
        return view('module.nfc.index',compact('nfcs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $crds = Crd::all();
        $erbs = Erb::all();
        return view('module.nfc.create',compact('crds','erbs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'crd_id'=>'required|string|max:34',
            'erb_id'=>'required|string|max:34',
            'count_global'=>'required|string|max:34',
            'count_between_cuts'=>'required|string|max:34',
            'time_global_between_cuts'=>'required|string|max:34',
            'time_between_cuts'=>'required|string|max:34',
            'prizes_count'=>'required|string|max:34',
            'num_serie'=>'required|string|max:34',
            'ssid'=>'required|string|max:34',
            'password'=>'required|string|max:34',
            'dns_server'=>'required|string|max:34',
            'ip_server'=>'required|string|max:34',
            'protocol'=>'required|string|max:34',
            'port'=>'required|string|max:34',
            'text'=>'required|string|max:34',
            
        ]);
        $nfc = new Nfc([
            'crd_id' => $request->get('crd_id'),
            'erb_id' => $request->get('erb_id'),
            'count_global' => $request->get('count_global'),
            'count_between_cuts' => $request->get('count_between_cuts'),
            'time_global_between_cuts' => $request->get('time_global_between_cuts'),
            'time_between_cuts' => $request->get('time_between_cuts'),
            'prizes_count' => $request->get('prizes_count'),
            'num_serie' => $request->get('num_serie'),
            'ssid' => $request->get('ssid'),
            'password' => $request->get('password'),
            'dns_server' => $request->get('dns_server'),
            'ip_server' => $request->get('ip_server'),
            'protocol' => $request->get('protocol'),
            'port' => $request->get('port'),
            'text' => $request->get('text')
            ]);
        $nfc->save();
        //return redirect(/nfc)->with('success','Nfc Generado Satisfactoriamente');
        toastr()->success('Nfc creado');
        return redirect()->route('nfc.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Nfc  $nfc
     * @return \Illuminate\Http\Response
     */
    public function show(Nfc $nfc)
    {
        //
        return view('module.nfc.show', compact('nfc'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Nfc  $nfc
     * @return \Illuminate\Http\Response
     */
    public function edit(Nfc $nfc)
    {
        //
        $crds = Crd::all();
        $erbs = Erb::all();
        return view('module.nfc.edit',compact('nfc','crds','erbs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Nfc  $nfc
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Nfc $nfc)
    {
        //
        $request->validate([
            'crd_id'=>'required|string|max:34',
            'erb_id'=>'required|string|max:34',
            'count_global'=>'required|string|max:34',
            'count_between_cuts'=>'required|string|max:34',
            'time_global_between_cuts'=>'required|string|max:34',
            'time_between_cuts'=>'required|string|max:34',
            'prizes_count'=>'required|string|max:34',
            'num_serie'=>'required|string|max:34',
            'ssid'=>'required|string|max:34',
            'password'=>'required|string|max:34',
            'dns_server'=>'required|string|max:34',
            'ip_server'=>'required|string|max:34',
            'protocol'=>'required|string|max:34',
            'port'=>'required|string|max:34',
            'text'=>'required|string|max:34',
        ]);
        $nfc_request = $request->all();
        $nfc->update($nfc_request);
        toastr()->warning('nfc actualizado');
        return redirect()->route('nfc.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Nfc  $nfc
     * @return \Illuminate\Http\Response
     */
    public function destroy(Nfc $nfc)
    {
        //
        $nfc->delete();
        //return reditec('/nfc'->with('success','nfc Eliminado Satisfactoriamente'));
        toastr()->error('nfc eliminado');
        return redirect()->route('nfc.index');
    }
}

resources/views/module/nfc/create.blade.php
@extends('adminlte::page')
@section('title', 'API ESP32')
@section('content_header')
   <!-- <h1>Menu Admin</h1>-->
@stop

@section('content')
@if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
@endif

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif
<!-- Main content -->
<section class="content">
      <div class="row">
        <div class="col-12">
            <div class="card card-success card-outline">
            <div class="card-header">
              <h3 class="card-title">Crear Nfc</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                  <!-- form start -->
            <form role="form" action="{{ route('user.store')}}" method="POST">
              @csrf
              <div class="card-body">
                <div class="form-group">
                  <label for="name">Nombre</label>
                  <input type="text" class="form-control" name="name" id="name"  placeholder="Introduce nombre" required>
                </div>
                <div class="form-group">
                  <label for="email">E-mail</label>
                  <input type="text" class="form-control" name="email" id="email"  placeholder="Introduce e-mail" required>
                </div>
                <div class="form-group">
                  <label for="password">Password</label>
                  <input type="password" class="form-control" name="password" id="password" placeholder="Introduce contraseña" required>
                </div>
                <div class="form-group">
                    <label for="name_role">Asignar tipo de usuario</label>
                        <select class="form-control" name="name_role" id="name_role"> 
                          @foreach($roles as $role)
                          <option>{{ $role->name }}</option>
                          @endforeach
                        </select>
              </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <a href="{{ route('user.index') }}" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-success pull-right" >Enviar</button>
              </div>
            </form>
            </div>
          <!-- /.card -->
          <!-- form-->
          <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content --> 
@stop


<!-- Main content -->
 <section class="content">
      <div class="row">
        <div class="col-xs-12">
            <div class="card card-success card-outline">
            <div class="card-header">
              <h3 class="card-title">Crear Nfc</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                  <!-- form start -->
            <form role="form" action="{{ route('nfc.store')}}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="crd_id">Crd Asignar</label>
                        <select class="form-control" name="crd_id" id="crd_id"> 
                          @foreach($crds as $crd)
                          <option>{{ $crd->id }}</option>
                          @endforeach
                        </select>
                </div>
                <div class="form-group">
                    <label for="erb_id">Erb Asignar</label>
                        <select class="form-control" name="erb_id" id="erb_id"> 
                          @foreach($erbs as $erb)
                          <option>{{ $erb->id }}</option>
                          @endforeach
                        </select>
                </div>
                <div class="form-group">
                  <label for="num_serie">Numero serie</label>
                  <input type="text" class="form-control" name="num_serie" id="num_serie"  placeholder="Introduce Numero de Serie" required>
                </div>
                <div class="form-group">
                  <label for="key_1">Clave 1</label>
                  <input type="text" class="form-control" name="key_1" id="key_1"  placeholder="Introduce clave 1" required>
                </div>
                <div class="form-group">
                  <label for="key_2">Clave 2</label>
                  <input type="text" class="form-control" name="key_2" id="key_2"  placeholder="Introduce clave 2" required>
                </div>
                <div class="form-group">
                  <label for="key_3">Clave 3</label>
                  <input type="text" class="form-control" name="key_3" id="key_3"  placeholder="Introduce clave 3" required>
                </div>
                <div class="form-group">
                  <label for="key_4">Clave 4</label>
                  <input type="text" class="form-control" name="key_4" id="key_4"  placeholder="Introduce clave 4" required>
                </div>
                <div class="form-group">
                  <label for="key_5">Clave 5</label>
                  <input type="text" class="form-control" name="key_5" id="key_5"  placeholder="Introduce clave 5" required>
                </div>
                <div class="form-group">
                  <label for="ssid">Ssid</label>
                  <input type="text" class="form-control" name="ssid" id="ssid"  placeholder="Introduce ssid" required>
                </div>
                <div class="form-group">
                  <label for="password">Password</label>
                  <input type="text" class="form-control" name="password" id="password"  placeholder="Introduce password" required>
                </div>
                <div class="form-group">
                  <label for="dns_server">Dns servidor</label>
                  <input type="text" class="form-control" name="dns_server" id="dns_server"  placeholder="Introduce dns" required>
                </div>
                <div class="form-group">
                  <label for="ip_server">Ip servidor</label>
                  <input type="text" class="form-control" name="ip_server" id="ip_server"  placeholder="Introduce ip" required>
                </div>
                <div class="form-group">
                  <label for="port">Puerto</label>
                  <input type="text" class="form-control" name="port" id="port"  placeholder="Introduce puerto" required>
                </div>
                <div class="form-group">
                    <label for="protocol">Protocolo</label>
                        <select class="form-control" name="protocol" id="protocol"> 
                          <option>JSON</option>
                          <option>Otro</option>
                        </select>
              </div>
                <div class="form-group">
                  <label for="text">Text</label>
                  <input type="text" min="0" class="form-control" name="text" id="text"  placeholder="Introduce text" required>
                </div>
                </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <a href="{{ route('nfc.index') }}" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-success pull-right" >Enviar</button>
              </div>
            </form>
          <!-- /.card -->
          <!-- form-->
 
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->   
@stop

@section('css')
    
@stop

@section('js')
@stop

resources/views/module/nfc/edit.blade.php
@extends('adminlte::page')
@section('title', 'API ESP32')
@section('content_header')
   <!-- <h1>Menu Admin</h1>-->
@stop

@section('content')
@if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
  @endif
 <!-- Main content -->
 <section class="content">
      <div class="row">
        <div class="col-xs-12">
            <div class="box card-warning card-outline">
            <div class="box-header">
              <h3 class="box-title">Editar Nfc</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                  <!-- form start -->
            <form role="form" action="{{ route('nfc.update',$nfc->id) }}" method="POST">
            @csrf
            @method('PUT')
              <div class="box-body">
              <!--'id', 'esp32_id', 'num_serie', 'key_1', 'key_2', 'key_3', 'key_4', 'key_5', 'ssid', 'password', 'dns_server', 'ip_server', 'protocol', 'port', 'text', -->
               <div class="form-group">
                    <label for="esp32_id">Esp32 Asignar</label>
                        <select class="form-control" name="esp32_id" id="esp32_id"> 
                          @foreach($esp32s as $esp32)
                          <option>{{ $esp32->id }}</option>
                          @endforeach
                        </select>
               </div>
                <div class="form-group">
                  <label for="num_serie">Numero Serie</label>
                  <input type="text" class="form-control" name="num_serie" id="num_serie"  placeholder="Introduce Numero de Serie" required value="{{ $nfc->num_serie }}">
                </div>
                <div class="form-group">
                  <label for="key_1">Clave 1</label>
                  <input type="text" class="form-control" name="key_1" id="key_1"  placeholder="Introduce Clave 1" required value="{{ $nfc->key_1 }}">
                </div>
                <div class="form-group">
                  <label for="key_2">Clave 2</label>
                  <input type="text" class="form-control" name="key_2" id="key_2"  placeholder="Introduce Clave 2" required value="{{ $nfc->key_2 }}">
                </div>
                <div class="form-group">
                  <label for="key_3">Clave 3</label>
                  <input type="text" class="form-control" name="key_3" id="key_3"  placeholder="Introduce Clave 3" required value="{{ $nfc->key_3 }}">
                </div>
                <div class="form-group">
                  <label for="key_4">Clave 4</label>
                  <input type="text" class="form-control" name="key_4" id="key_4"  placeholder="Introduce Clave 4" required value="{{ $nfc->key_4 }}">
                </div>
                <div class="form-group">
                  <label for="key_5">Clave 5</label>
                  <input type="text" class="form-control" name="key_5" id="key_5"  placeholder="Introduce Clave 5" required value="{{ $nfc->key_5 }}">
                </div>
                <div class="form-group">
                  <label for="ssid">Ssid</label>
                  <input type="text" class="form-control" name="ssid" id="ssid"  placeholder="Introduce ssid" required value="{{ $nfc->ssid }}">
                </div>
                <div class="form-group">
                  <label for="password">Password</label>
                  <input type="text" class="form-control" name="password" id="password"  placeholder="Introduce password" required value="{{ $nfc->password }}">
                </div>
                <div class="form-group">
                  <label for="dns_server">Dns Servidor</label>
                  <input type="text" class="form-control" name="dns_server" id="dns_server"  placeholder="Introduce dns" required value="{{ $nfc->dns_server }}">
                </div>
                <div class="form-group">
                  <label for="ip_server">Ip Servidor</label>
                  <input type="text" class="form-control" name="ip_server" id="ip_server"  placeholder="Introduce ip" required value="{{ $nfc->ip_server }}">
                </div>
                <div class="form-group">
                  <label for="port">port</label>
                  <input type="text" class="form-control" name="port" id="port"  placeholder="Introduce puerto" required value="{{ $nfc->port }}">
                </div>
                <div class="form-group">
                    <label for="protocol">Protocolo</label>
                        <select class="form-control" name="protocol" id="protocol"> 
                          <option>JSON</option>
                          <option>Otro</option>
                        </select>
              </div>
                <div class="form-group">
                  <label for="text">Text</label>
                  <input type="text" class="form-control" name="text" id="text"  placeholder="Introduce text" required value="{{ $nfc->text }}">
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <a href="{{ route('nfc.index') }}" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-warning pull-right" >Enviar</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
          <!-- form-->
 
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->   
@stop

@section('css')
    
@stop

@section('js')
@stop