routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::resource('region', 'RegionController')->middleware('auth');
Route::resource('user', 'UserController')->middleware('auth');
Route::resource('role', 'RoleController')->middleware('auth');
Route::resource('assignment', 'AssignmentController')->middleware('auth');
Route::resource('permission', 'PermissionController')->middleware('auth');
Route::resource('crd', 'CrdController')->middleware('auth');
Route::resource('erb', 'ErbController')->middleware('auth');
Route::resource('counter', 'CounterController')->middleware('auth');
Route::resource('qr', 'QrController')->middleware('auth');
Route::resource('nfc', 'NfcController')->middleware('auth');
Route::get('sensor/chart/{id}', 'SensorController@chart')->name('sensor.chart')->middleware('auth');
Route::resource('sensor', 'SensorController')->middleware('auth');
Route::resource('statistical', 'StatisticalController')->middleware('auth');
Route::resource('probeestimating', 'ProbeEstimatingController')->middleware('auth');
Route::resource('classname', 'ClassNameController')->middleware('auth');
Route::resource('file', 'FileController')->middleware('auth');
Route::resource('historialcounter', 'HistorialCounterController')->middleware('auth');
Route::resource('historialcrd', 'HistorialCrdController')->middleware('auth');
Route::resource('historialerb', 'HistorialErbController')->middleware('auth');
Route::resource('historialqr', 'HistorialQrController')->middleware('auth');
Route::resource('historialnfc', 'HistorialNfcController')->middleware('auth');
Route::get('historialsensor/chart/{id}', 'HistorialSensorController@chart')->name('historialsensor.chart')->middleware('auth');
Route::resource('historialsensor', 'HistorialSensorController')->middleware('auth');
Route::resource('historialstatistical', 'HistorialStatisticalController')->middleware('auth');
Auth::routes();

app/HistorialStatistical.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class HistorialStatistical extends Model
{
    //
}

app/Http/Controllers/HistorialStatisticalController.php
<?php

namespace App\Http\Controllers;

use App\HistorialStatistical;
use Illuminate\Http\Request;

class HistorialStatisticalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\HistorialStatistical  $historialStatistical
     * @return \Illuminate\Http\Response
     */
    public function show(HistorialStatistical $historialStatistical)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\HistorialStatistical  $historialStatistical
     * @return \Illuminate\Http\Response
     */
    public function edit(HistorialStatistical $historialStatistical)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\HistorialStatistical  $historialStatistical
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, HistorialStatistical $historialStatistical)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\HistorialStatistical  $historialStatistical
     * @return \Illuminate\Http\Response
     */
    public function destroy(HistorialStatistical $historialStatistical)
    {
        //
    }
}

resources/views/module/historialstatistical/create.blade.php
@extends('adminlte::page')
@section('title', 'Hotspot-Historial-Qr')
@section('content_header')
   <!-- <h1>Menu Admin</h1>-->
@stop

@section('content')
@if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
  @endif

@if ($message = Session::get('success'))

<div class="alert alert-success">

    <p>{{ $message }}</p>

</div>
@endif

 <!-- Main content -->
 <section class="content">
      <div class="row">
        <div class="col-12">
            <div class="card">
            <div class="card-header">
              <h3 class="card-title">Crear Historial Qr</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <!-- form start -->
            <form role="form" action="{{ route('historialqr.store')}}" method="POST">
              @csrf
              <div class="card-body">
              <div class="form-group">
                    <label for="qr_id">Qr Id</label>
                        <select class="form-control" name="qr_id" id="qr_id"> 
                          {{--<option selected="true">{{ $qr->qr_asign }}</option>--}}
                          @foreach($qrs as $qr)
                          <option>{{ $qr->id }}</option>
                          @endforeach
                        </select>
              </div>
                <div class="form-group">
                  <label for="name_machine">Nombre</label>
                  <input type="text" class="form-control" name="name_machine" id="name_machine"  placeholder="Introduce maquina" required>
                </div>
                <div class="form-group">
                  <label for="nick_name">Alias</label>
                  <input type="text" class="form-control" name="nick_name" id="nick_name"  placeholder="Introduce alias" required>
                </div>
                <div class="form-group">
                  <label for="qr_serie">Qr Serie</label>
                  <input type="text" class="form-control" name="qr_serie" id="qr_serie"  placeholder="Introduce alias" required>
                </div>
                <div class="form-group">
                  <label for="coins">Coins</label>
                  <input type="text" class="form-control" name="coins" id="coins"  placeholder="Introduce coins" required>
                </div>
                <div class="form-group">
                  <label for="uploaded">Actualido</label>
                  <input type="text" class="form-control" name="uploaded" id="uploaded"  placeholder="Introduce 0-sin actualizar 1-actualizado" required>
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <a href="{{ route('historialqr.index') }}" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-success pull-right" >Enviar</button>
              </div>
            </form>
            </div>
            <!-- /.card -->
            <!-- form-->
            <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->   
@stop

@section('footer') 
<div class="pull-right hidden-xs"><b>Version</b> 2.0.0<strong>  Copyright &copy; 2020 <a href="http://hotspot.local/home" target="_blank">Hotspot</a>.</strong>  Todo los derechos Reservados.</div> 
@stop

@section('css')
@toastr_css    
@stop

@section('js')
@toastr_js
@toastr_render
@stop

resources/views/module/historialstatistical/edit.blade.php
@extends('adminlte::page')
@section('title', 'Hotspot-Historial-Qr')
@section('content_header')
   <!-- <h1>Menu Admin</h1>-->
@stop

@section('content')
@if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
@endif

@if ($message = Session::get('success'))

<div class="alert alert-success">

    <p>{{ $message }}</p>

</div>
@endif

 <!-- Main content -->
 <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Editar Historial Qr</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <!-- form start -->
            <form role="form" action="{{ route('historialqr.update',$historialqr->id) }}" method="POST">
            @csrf
            @method('PUT')
              <div class="card-body">
              <div class="form-group">
                    <label for="qr_id">Qr Id</label>
                        <select class="form-control" name="qr_id" id="qr_id" value="{{ $historialqr->qr_id }}">
                          @foreach($qrs as $qr)
                          <option>{{ $qr->id }}</option>
                          @endforeach
                        </select>
              </div>
                <div class="form-group">
                  <label for="name_machine">Maquina</label>
                  <input type="text" class="form-control" name="name_machine" id="name_machine"  placeholder="Introduce Num serie" required value="{{ $historialqr->name_machine }}" />
                </div>
                <div class="form-group">
                  <label for="nick_name">Nick</label>
                  <input type="text" class="form-control" name="nick_name" id="nick_name"  placeholder="Introduce Num serie" required value="{{ $historialqr->nick_name }}" />
                </div>
                <div class="form-group">
                  <label for="qr_serie">Qr Serie</label>
                  <input type="text" class="form-control" name="qr_serie" id="qr_serie"  placeholder="Introduce Num serie" required value="{{ $historialqr->qr_serie }}" />
                </div>
                <div class="form-group">
                  <label for="coins">Coins</label>
                  <input type="text" class="form-control" name="coins" id="coins"  placeholder="Introduce alias" required value="{{ $historialqr->coins }}" />
                </div>
                <div class="form-group">
                  <label for="uploaded">Actualizado</label>
                  <input type="text" class="form-control" name="uploaded" id="uploaded"  placeholder="Introduce alias" required value="{{ $historialqr->uploaded }}" />
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <a href="{{ route('historialqr.index') }}" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-warning pull-right" >Enviar</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
          <!-- form-->
          <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content --> 
@stop

@section('footer') 
<div class="pull-right hidden-xs"><b>Version</b> 2.0.0<strong>  Copyright &copy; 2020 <a href="http://hotspot.local/home" target="_blank">Hotspot</a>.</strong>  Todo los derechos Reservados.</div> 
@stop

@section('css')
@toastr_css 
@stop

@section('js')
@toastr_js
@toastr_render
@stop

resources/views/module/historialstatistical/index.blade.php
@extends('adminlte::page')
@section('title', 'Hotspot-Historial-Qr')
@section('content_header')
   <!-- <h1>Menu Admin</h1>-->
@stop

@section('content')
@if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
@endif

@if ($message = Session::get('success'))

<div class="alert alert-success">

    <p>{{ $message }}</p>

</div>
@endif

 <!-- Main content -->
 <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Tabla Historial Qr</h3>
              <a class="btn btn-xs btn-success float-right" href="{{ route('historialqr.create') }}" role="button"><span class="fas fa-plus"></span></a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="historialqrTable" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Qr Id</th>
                  <th>Maquina</th>
                  <th>Alias</th>
                  <th>QrSerie</th>
                  <th>Coins</th>
                  <th>Actualizado</th>
                  <th>FechaCreacion</th>
                  <th>FechaMoficiacion</th>
                  <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach($historialqrs as $historialqr)
                <tr>
                    <td>{{ $historialqr->id }}</td>
                    <td>{{ $historialqr->qr_id }}</td>
                    <td>{{ $historialqr->name_machine }}</td>
                    <td>{{ $historialqr->nick_name }}</td>      
                    <td>{{ $historialqr->qr_serie }}</td>
                    <td>{{ $historialqr->coins }}</td>
                    <td>{{ $historialqr->uploaded }}</td>
                    <td>{{ $historialqr->created_at }}</td>
                    <td>{{ $historialqr->updated_at }}</td>
                    <td>
                      <form role="form" action="{{ route('historialqr.destroy',$historialqr->id) }}" method="POST">
                      <a class="btn btn-info btn-xs" href="{{ route('historialqr.show',$historialqr->id) }}" role="button"><span class="fas fa-eye"></span></a> 
                      <a class="btn btn-warning btn-xs"  href="{{ route('historialqr.edit',$historialqr->id) }}" role="button"><span class="fas fa-pen"></span></a>
                      @csrf
                      @method('DELETE')
                      <button class="btn btn-danger btn-xs" type="submit"><span class="fas fa-trash"></span></button>
                      </form>
                    </td>
                </tr>
                @endforeach
                </tbody>
               <!-- <tfoot>
                 <tr>
                 <th>Id</th>
                  <th>Crd_Id</th>
                  <th>Erb_id</th>
                  <th>QrSerie</th>
                  <th>Coins</th>
                  <th>Actualizado</th>
                  <th>FechaCreacion</th>
                  <th>FechaMoficiacion</th>
                  <th>Acciones</th>
                </tr>
                </tfoot>-->
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content --> 
@stop

@section('footer') 
<div class="pull-right hidden-xs"><b>Version</b> 2.0.0<strong>  Copyright &copy; 2020 <a href="http://hotspot.local/home" target="_blank">Hotspot</a>.</strong>  Todo los derechos Reservados.</div> 
@stop

@section('css')
@toastr_css 
@stop

@section('js')
@toastr_js
@toastr_render
<script>
  $(function () {
     $('#historialqrTable').DataTable({  
      'paging'      : true,
      'lengthChange': true,
      'searching'   : true,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false,
      'scrollX'     : true,
      'scrollY'     : false,
      'scrollCollapse': false,
      'language': {'url': '//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json'}   
    })
  });
</script>
@stop

resources/views/module/historialstatistical/show.blade.php
@extends('adminlte::page')
@section('title', 'Hotspot-Historial-Qr')
@section('content_header')
   <!-- <h1>Menu Admin</h1>-->
@stop

@section('content')
@if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
@endif

@if ($message = Session::get('success'))

<div class="alert alert-success">

    <p>{{ $message }}</p>

</div>
@endif

 <!-- Main content -->
 <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Tabla Historial Qr</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <form role="form">
              <div class="card-body">
                <div class="form-group">
                  <label for="id">Id</label>
                  <input type="text" class="form-control" value="{{ $historialqr->id }}" readonly="readonly"/>
                </div>
                <div class="form-group">
                  <label for="qr_id">Qr Id</label>
                  <input type="text" class="form-control" value="{{ $historialqr->qr_id }}" readonly="readonly"/>
                </div>
                <div class="form-group">
                  <label for="name_machine">Maquina</label>
                  <input type="text" class="form-control" value="{{ $historialqr->name_machine }}" readonly="readonly"/>
                </div>
                <div class="form-group">
                  <label for="nick_name">Alias</label>
                  <input type="text" class="form-control" value="{{ $historialqr->nick_name }}" readonly="readonly"/>
                </div>
                <div class="form-group">
                  <label for="qr_serie">Qr Serie</label>
                  <input type="text" class="form-control" value="{{ $historialqr->qr_serie }}" readonly="readonly"/>
                </div>
                <div class="form-group">
                  <label for="coins">Coins</label>
                  <input type="text" class="form-control" value="{{ $historialqr->coins }}" readonly="readonly"/>
                </div>
                <div class="form-group">
                  <label for="uploaded">Actualizado</label>
                  <input type="text" class="form-control" value="{{ $historialqr->uploaded }}" readonly="readonly"/>
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <a href="{{ route('historialqr.index') }}" class="btn btn-info pull-right">Regresar</a>
              </div>
            </form>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content --> 
@stop

@section('footer') 
<div class="pull-right hidden-xs"><b>Version</b> 2.0.0<strong>  Copyright &copy; 2020 <a href="http://hotspot.local/home" target="_blank">Hotspot</a>.</strong>  Todo los derechos Reservados.</div> 
@stop

@section('css')
@toastr_css
@stop

@section('js')
@toastr_js
@toastr_render
@stop