routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::resource('region', 'RegionController')->middleware('auth');
Route::resource('user', 'UserController')->middleware('auth');
Route::resource('role', 'RoleController')->middleware('auth');
Route::resource('assignment', 'AssignmentController')->middleware('auth');
Route::resource('permission', 'PermissionController')->middleware('auth');
Route::resource('crd', 'CrdController')->middleware('auth');
Route::resource('erb', 'ErbController')->middleware('auth');
Route::resource('counter', 'CounterController')->middleware('auth');
Route::resource('qr', 'QrController')->middleware('auth');
Route::resource('nfc', 'NfcController')->middleware('auth');
Route::get('sensor/chart/{id}', 'SensorController@chart')->name('sensor.chart')->middleware('auth');
Route::resource('sensor', 'SensorController')->middleware('auth');
Route::resource('statistical', 'StatisticalController')->middleware('auth');
Route::resource('probeestimating', 'ProbeEstimatingController')->middleware('auth');
Route::resource('classname', 'ClassNameController')->middleware('auth');
Route::resource('file', 'FileController')->middleware('auth');
Route::resource('historialcounter', 'HistorialCounterController')->middleware('auth');
Route::resource('historialcrd', 'HistorialCrdController')->middleware('auth');
Route::resource('historialerb', 'HistorialErbController')->middleware('auth');
Route::resource('historialqr', 'HistorialQrController')->middleware('auth');
Route::resource('historialnfc', 'HistorialNfcController')->middleware('auth');
Route::get('historialsensor/chart/{id}', 'HistorialSensorController@chart')->name('historialsensor.chart')->middleware('auth');
Route::resource('historialsensor', 'HistorialSensorController')->middleware('auth');
Route::resource('historialstatistical', 'HistorialStatisticalController')->middleware('auth');
Auth::routes();

app/Http/Controllers/AssignmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Session;
use App\User;
use App\Crd;
use App\Erb;
use App\Role;
use App\Permission;
use DB;

class AssignmentController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the Role.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $models = array_keys(Config::get('laratrust.user_models'));
        $users = User::all();
        $array_roles = array();
        $array_permissions = array();
        foreach (Role::all() as $key_role => $role) {
        $array_roles[$key_role] = $role->name;
        }
        foreach (Permission::all() as $key_permission => $permission) {
        $array_permissions[$key_permission] = $permission->name;
        }
        foreach ($users as $key_user => $user) {
        $options = [
            'validate_all' => true,
            'return_type' => 'both'
        ];
        $user->ability = $user->ability(
            [$array_roles[0]],
            [$array_permissions[0]],
            $options
        );
        }

        foreach ($users as $key_user => $user) {
            $options = [
                'validate_all' => true,
                'return_type' => 'both'
            ];
            $assignment = array();
            foreach (Role::all() as $key_role => $role)
            {
                if($user->hasRole($role->name))
                {
                    $user->num_role += 1;
                    foreach (Permission::all() as $key_permission => $permission) {
                        if($user->hasPermission($permission->name))
                        {
                            $user->num_permission += 1;
                            $assignment[$key_permission] = $user->ability(
                                ['root', 'admin', 'super', 'user', 'disable'],
                                [$permission->name],
                                [
                                'validate_all' => true,
                                'return_type' => 'both'
                                ]
                            );
                        }
                    } 
                }
            }
            $user->assignment = $assignment;
        }
        return view('module.assignment.index',compact('models','users'));
    }

    /**
     * Show the form for creating a new resource for Role.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('module.role.create');
    }

    /**
     * Store a newly created resource in storage for Role.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $createRole = Role::create([
            'name' => $request->get('name'),
            'display_name' => $request->get('display_name'), // optional
            'description' => $request->get('description'), // optional
            ]);
        toastr()->success('Role creado');
        return redirect()->route('role.index');
    }

    /**
     * Display the specified resource for Role.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($user)
    {
        //
        dd($user);
        return view('module.role.show',compact('user'));
    }

    public function edit($id)
    {
        $role = Role::findOrFail($id);
        return view('module.role.edit',compact('role'));
    }

    /**
     * Update the specified resource in storage for Role.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::findOrFail($id);

        $data = $request->validate([
            'display_name' => 'nullable|string',
            'description' => 'nullable|string',
        ]);

        $role->update($data);
        toastr()->warning('Role actualizado satisfactoriamente');
        return redirect()->route('role.index');
    }

    /**
     * Remove the specified resource from storage for Role.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();
        //return redirect('/role')->with('success', 'Role Eliminado!');
        toastr()->error('Role eliminado');
        return redirect()->route('role.index');
    }
}

resources/views/module/assignment/create.blade.php
@extends('adminlte::page')
@section('title', 'Hotspot-Role')
@section('content_header')
   <!-- <h1>Menu Admin</h1>-->
@stop

@section('content')
@if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
@endif

@if ($message = Session::get('success'))

<div class="alert alert-success">

    <p>{{ $message }}</p>

</div>
@endif
 <!-- Main content -->
 <section class="content">
      <div class="row">
        <div class="col-12">
            <div class="card card-success card-outline">
            <div class="card-header">
              <h3 class="card-title">Crear Role</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                  <!-- form start -->
            <form role="form" action="{{ route('role.store')}}" method="POST">
              @csrf
              <div class="card-body">
                <div class="form-group">
                  <label for="name">Nom-Codigo</label>
                  <input type="text" class="form-control" name="name" id="name"  placeholder="Introduce un nombre del rol para codigo" required>
                </div>
                <div class="form-group">
                  <label for="display_name">Nom-Vista</label>
                  <input type="text" class="form-control" name="display_name" id="display_name"  placeholder="Introduce el nombre visible" required>
                </div>
                <div class="form-group">
                  <label for="description">Descripcion</label>
                  <input type="description" class="form-control" name="description" id="description" placeholder="Introduce descricpion del rol" required>
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <a href="{{ route('role.index') }}" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-success pull-right" >Enviar</button>
              </div>
            </form>
            </div>
          <!-- /.card -->
          <!-- form-->
          <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content --> 
@stop

@section('footer') 
<div class="pull-right hidden-xs"><b>Version</b> 2.0.0<strong>  Copyright &copy; 2020 <a href="http://hotspot.local/home" target="_blank">Hotspot</a>.</strong>  Todo los derechos Reservados.</div> 
@stop

@section('css')
@toastr_css 
@stop

@section('js')
@toastr_js
@toastr_render
@stop

resources/views/module/assignment/edit.blade.php
@extends('adminlte::page')
@section('title', 'Hotspot-Role')
@section('content_header')
   <!-- <h1>Menu Admin</h1>-->
@stop

@section('content')
@if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
  @endif

@if ($message = Session::get('success'))

<div class="alert alert-success">

    <p>{{ $message }}</p>

</div>
@endif

 <!-- Main content -->
 <section class="content">
      <div class="row">
        <div class="col-12">
            <div class="card card-warning card-outline">
            <div class="card-header">
              <h3 class="card-title">Editar Role</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                  <!-- form start -->
            <form role="form" action="{{ route('role.update',$role->id) }}" method="POST">
            @csrf
            @method('PUT')
              <div class="card-body">
                <div class="form-group">
                  <label for="name">Nom-Codigo</label>
                  <input type="text" class="form-control" name="name" id="name"  placeholder="Introduce un nombre de role para codigo" required value="{{ $role->name }}" readonly/>
                </div>
                <div class="form-group">
                  <label for="display_name">Nom-Vista</label>
                  <input type="display_name" class="form-control" name="display_name" id="display_name"  placeholder="Introduce el nombre visible" required value="{{ $role->display_name }}" />
                </div>
                <div class="form-group">
                  <label for="description">Descripcion</label>
                  <input type="description" class="form-control" name="description" id="description" placeholder="Introduce descricpion del role" required value="{{ $role->description }}" />
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <a href="{{ route('role.index') }}" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-warning pull-right" >Enviar</button>
              </div>
            </form>
            </div>
          <!-- /.card -->
          <!-- form-->
          <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content --> 
@stop

@section('footer') 
<div class="pull-right hidden-xs"><b>Version</b> 2.0.0<strong>  Copyright &copy; 2020 <a href="http://hotspot.local/home" target="_blank">Hotspot</a>.</strong>  Todo los derechos Reservados.</div> 
@stop

@section('css')
@toastr_css 
@stop

@section('js')
@toastr_js
@toastr_render
@stop

resources/views/module/assignment/index.blade.php
@extends('adminlte::page')
@section('title', 'Hotspot-Assignment')
@section('content_header')
   <!-- <h1>Menu Admin</h1>-->
@stop

@section('content')
@if ($errors->any())
    <div class="alert alert-danger">
      <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
      </ul>
    </div><br />
@endif

@if ($message = Session::get('success'))
    <div class="alert alert-success">
      <p>{{ $message }}</p>
    </div>
@endif

 <!-- Main content -->
 <section class="content">
      <div class="row">
        <div class="col-12">
            <div class="card card-primary card-outline">
            <div class="card-header">
              <h3 class="card-title ">Asignacion de Roles y Permisos</h3>
              <a class="btn btn-xs btn-success float-right" href="{{ route('assignment.create') }}" role="button"><span class="fas fa-plus"></span></a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <div class="form-group">
                <h3 class="card-title ">Usuarios</h3><br>
                <select class="form-control" name="model" id="model">
                  @foreach($models as $model)
                    <option>{{ $model }}</option>
                  @endforeach
                </select>
              </div>
              <table id="assignmentTable" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Id</th>
                  <th>Nombre</th>
                  <th>NumRole</th>
                  <th>NumPermiso</th>
                  <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->num_role }}</td>
                    <td>{{ $user->num_permission }}</td>
                    <td>
                     {{-- <form role="form" action="{{ route('assignment.destroy',$user->id) }}" method="POST"> --}}
                      {{-- <a class="btn btn-info btn-xs" href="{{ route('assignment.show',$user) }}" role="button"><span class="fas fa-eye"></span></a> --}}
                      <a class="btn btn-warning btn-xs"  href="{{ route('assignment.edit',$user->id) }}" role="button"><span class="fas fa-pen"></span></a>
                      @csrf
                      @method('DELETE')
                      {{-- <button class="btn btn-danger btn-xs" type="submit"><span class="fas fa-trash"></span></button> --}}
                     {{-- </form> --}}
                    </td>
                </tr>
                @endforeach
                </tbody>
               <!-- <tfoot>
                <tr>
                  <th>Id</th>
                  <th>Nom-Codigo</th>
                  <th>Nom-Vista</th>
                  <th>Descripcion</th>
                  <th>FechaCreacion</th>
                  <th>FechaMoficiacion</th>
                  <th>Acciones</th>
                </tr>
                </tfoot>-->
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->  
    
@stop

@section('footer') 
<div class="pull-right hidden-xs"><b>Version</b> 2.0.0<strong>  Copyright &copy; 2020 <a href="http://hotspot.local/home" target="_blank">Hotspot</a>.</strong>  Todo los derechos Reservados.</div> 
@stop

@section('css')
@toastr_css 
@stop

@section('js')
@toastr_js
@toastr_render
<script>
  $(function () {
     $('#assignmentTable').DataTable({  
      'paging'      : true,
      'lengthChange': true,
      'searching'   : true,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false,
      'scrollX'     : true,
      'scrollY'     : false,
      'scrollCollapse': false,
      'language': {'url': '//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json'}   
    })
  });
</script>
@stop

resources/views/module/assignment/show.blade.php
@extends('adminlte::page')
@section('title', 'Hotspot-Assignment')
@section('content_header')
   <!-- <h1>Menu Admin</h1>-->
@stop

@section('content')
@if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
  @endif

@if ($message = Session::get('success'))

<div class="alert alert-success">

    <p>{{ $message }}</p>

</div>
@endif

 <!-- Main content -->
 <section class="content">
      <div class="row">
        <div class="col-12">
            <div class="card card-info card-outline">
            <div class="card-header">
              <h3 class="card-title">Ver Usuario</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                  <!-- form start -->
            <form role="form">
              <div class="card-body">
                <div class="form-group">
                  <label for="name">Nom-Codigo</label>
                  <input type="text" class="form-control" value="{{ $role->name }}" readonly="readonly"/>
                </div>
                <div class="form-group">
                  <label for="display_name">Nom-Vista</label>
                  <input type="text" class="form-control" value="{{ $role->display_name }}" readonly="readonly"/>
                </div>
                <div class="form-group">
                  <label for="description">Descripcion</label>
                  <input type="text" class="form-control" value="{{ $role->description }}" readonly="readonly"/>
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <a href="{{ route('role.index') }}" class="btn btn-info pull-right">Regresar</a>
                </div>
            </form>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->   
@stop

@section('footer') 
<div class="pull-right hidden-xs"><b>Version</b> 2.0.0<strong>  Copyright &copy; 2020 <a href="http://hotspot.local/home" target="_blank">Hotspot</a>.</strong>  Todo los derechos Reservados.</div> 
@stop

@section('css')
@toastr_css
@stop

@section('js')
@toastr_js
@toastr_render
@stop